Repository P3HPC/code-base-investigator, pull requests merged in 2024-02, with the labels that each got.

#42 Add support for exclude patterns
  README.md
  codebasin.py
  codebasin/config.py
  codebasin/schema/config.schema
  codebasin/walkers/platform_mapper.py
  setup.py
  tests/exclude/__init__.py
  tests/exclude/commands.json
  tests/exclude/exclude.yaml
  tests/exclude/src/excluded_extension.f90
  tests/exclude/src/excluded_name.cpp
  tests/exclude/src/included.cpp
  tests/exclude/src/thirdparty/library.cpp
  tests/exclude/test_exclude.py
Labels: enhancement

#44 Templates for pull requests and issues
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#48 Adjust pull request template formatting
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#51 Catch all exceptions and convert them to errors
  codebasin.py
Labels: enhancement

#52 Fix unintended skipping of `bandit` in `pre-commit` hooks and added scan specifications
  .bandit
  .pre-commit-config.yaml
Labels: bug

#53 Remove flake8-bandit from pre-commit
  .pre-commit-config.yaml
Labels: bug

#56 Replace importcfg.json with config TOML file
  MANIFEST.in
  codebasin/config.py
  codebasin/schema/config.schema
  codebasin/schema/importcfg.schema
  codebasin/util.py
  tests/schema/test_schema.py
Labels: enhancement

#57 Restore missing {} to report outputs
  codebasin/report.py
Labels: bug

#49 Add option to define platforms on the command line
  codebasin.py
  codebasin/config.py
  codebasin/finder.py
Labels: enhancement

#59 Replace --rootdir (-r) with --source-dir (-S)
  codebasin.py
Labels: enhancement

#63 Add schema file required by functionality from #56
  codebasin/schema/cbiconfig.schema
Labels: bug

#62 Deprecate unmaintained functionality
  codebasin.py
Labels: documentation

#64 Rename codebasin.py to codebasin
  README.md
  bin/codebasin
  setup.py
Labels: bug

#65 Add Github action to run `unittest`
  .github/workflows/run-unittest.yml
Labels: enhancement

#61 Add TOML files required by tests from #56
  tests/schema/cbiconfig.toml
  tests/schema/invalid_cbiconfig.toml
Labels: bug

#60 Replace YAML config files with TOML analysis files
  MANIFEST.in
  bin/codebasin
  codebasin/schema/analysis.schema
  codebasin/util.py
  tests/schema/analysis.toml
  tests/schema/invalid_analysis.toml
  tests/schema/test_schema.py
Labels: enhancement
